resource_types:
- name: build-metadata
  type: docker-image
  source:
    repository: mastertinner/build-metadata-resource

resources:
- name: pipeline-promotion
  type: git
  source:
    uri: https://github.com/crsimmons/pipeline-promotion.git
    username: ((github_username))
    password: ((github_access_token))

- name: cf-deployment
  type: github-release
  source:
    owner: cloudfoundry
    repository: cf-deployment
    access_token: ((github_access_token))

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git
    username: ((github_username))
    password: ((github_access_token))

- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    username: ((github_username))
    password: ((github_access_token))
    branch: master

- name: pcf-ops-image
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops

- name: build-metadata
  type: build-metadata

jobs:
- name: terraform
  plan:
  - in_parallel:
    - get: pipeline-promotion
      version: ((resource_version_pipeline-promotion))
      trigger: true
    - get: pcf-ops-image
      version: ((resource_version_pcf-ops-image))
  - task: terraform
    image: pcf-ops-image
    file: pipeline-promotion/tasks/terraform.yml
    params:
      PIPELINE_PROMOTION_VERSION: ((resource_version_pipeline-promotion))

- name: deploy-director
  plan:
  - in_parallel:
    - get: bosh-deployment
      version: ((resource_version_bosh-deployment))
      trigger: true
    - get: pipeline-promotion
      trigger: true
      passed: [terraform]
    - get: pcf-ops-image
      passed: [terraform]
  - task: deploy-director
    image: pcf-ops-image
    file: pipeline-promotion/tasks/deploy-director.yml
    params:
      BOSH_DEPLOYMENT_VERSION: ((resource_version_bosh-deployment))

- name: deploy-cf
  plan:
  - in_parallel:
    - get: cf-deployment
      version: ((resource_version_cf-deployment))
      trigger: true
    - get: pipeline-promotion
      trigger: true
      passed: [deploy-director]
    - get: pcf-ops-image
      passed: [deploy-director]
    - get: bosh-deployment
      passed: [deploy-director]
      trigger: true
  - task: deploy-cf
    image: pcf-ops-image
    file: pipeline-promotion/tasks/deploy-cf.yml
    params:
      CF_DEPLOYMENT_VERSION: ((resource_version_cf-deployment))

- name: smoke-test
  plan:
  - in_parallel:
    - get: cf-smoke-tests
      version: ((resource_version_cf-smoke-tests))
      trigger: true
    - get: pcf-ops-image
      passed: [deploy-cf]
    - get: bosh-deployment
      passed: [deploy-cf]
      trigger: true
    - get: cf-deployment
      passed: [deploy-cf]
      trigger: true
    - get: pipeline-promotion
      trigger: true
      passed: [deploy-cf]
  - task: smoke-test
    image: pcf-ops-image
    file: pipeline-promotion/tasks/smoke-test.yml
    params:
      SMOKE_TESTS_VERSION: ((resource_version_cf-smoke-tests))

- name: promote-versions
  plan:
  - in_parallel:
    - get: cf-smoke-tests
      trigger: true
      passed: [smoke-test]
    - get: cf-deployment
      trigger: true
      passed: [smoke-test]
    - get: bosh-deployment
      trigger: true
      passed: [smoke-test]
    - get: pipeline-promotion
      trigger: true
      passed: [smoke-test]
    - get: pcf-ops-image
      trigger: true
      passed: [smoke-test]
    - get: build-metadata
  - task: generate-versions
    image: pcf-ops-image
    file: pipeline-promotion/tasks/generate-versions.yml
    params:
      CONCOURSE_URL: ((concourse_url))
      CONCOURSE_USERNAME: ((concourse_username))
      CONCOURSE_PASSWORD: ((concourse_password))
