---
platform: linux

inputs:
  - name: pipeline-promotion

params:
  BOSH_DEPLOYMENT_VERSION:

run:
  path: bash
  args:
  - "-euc"
  - |
    printf "Deploying Director with\nbosh-deployment %s" "${BOSH_DEPLOYMENT_VERSION}"
