---
platform: linux

inputs:
  - name: pipeline-promotion

params:
  CF_DEPLOYMENT_VERSION:

run:
  path: bash
  args:
  - "-euc"
  - |
    printf "Deploying CF with\ncf-deployment %s" "${CF_DEPLOYMENT_VERSION}"
