---
platform: linux

inputs:
  - name: pipeline-promotion

params:
  PROMETHEUS_GIT_VERSION:
  PROMETHEUS_RELEASE_VERSION:

run:
  path: bash
  args:
  - "-euc"
  - |
    printf "Deploying Prometheus with\nprometheus-git %s\nprometheus-release %s" "${PROMETHEUS_GIT_VERSION}" "${PROMETHEUS_RELEASE_VERSION}"
