---
platform: linux

inputs:
  - name: pipeline-promotion
  - name: build-metadata

outputs:
  - name: resource-versions

params:
  CONCOURSE_URL:
  CONCOURSE_USERNAME:
  CONCOURSE_PASSWORD:

run:
  path: pipeline-promotion/tasks/generate-versions.sh
