---
platform: linux

inputs:
  - name: pipeline-promotion
  - name: build-metadata

outputs:
  - name: resource-versions

params:
  CONCOURSE_URL:
  CONCOURSE_USERNAME:
  CONCOURSE_PASSWORD:

run:
  path: bash
  args:
  - "-euc"
  - |
    source pipeline-promotion/tasks/fly-login.sh

    export ATC_BEARER_TOKEN=$(bosh int --path /targets/ci/token/value ~/.flyrc)

    PIPELINE_NAME=$(build-metadata/build-pipeline-name)

    team=$(cat build-metadata/build-team-name)
    job=$(cat build-metadata/build-job-name)

    stopover.v2 ${CONCOURSE_URL} $team ${PIPELINE_NAME} $job $(cat build-metadata/build-name) > resource-versions/versions.yml
