---
platform: linux

inputs:
  - name: pipeline-promotion

params:
  SMOKE_TESTS_VERSION:

run:
  path: bash
  args:
  - "-euc"
  - |
    printf "Running smoke tests with\nsmoke-tests %s" "${SMOKE_TESTS_VERSION}"
