---
platform: linux

inputs:
  - name: pipeline-promotion

params:
  PIPELINE_PROMOTION_VERSION:

run:
  path: bash
  args:
  - "-euc"
  - |
    printf "Applying terraform with\npipeline-promotion %s" "${PIPELINE_PROMOTION_VERSION}"
